[2022-07-22 09:46:48,095] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: traffic_flow_dag.read_data manual__2022-07-22T06:46:44.015483+00:00 [queued]>
[2022-07-22 09:46:48,099] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: traffic_flow_dag.read_data manual__2022-07-22T06:46:44.015483+00:00 [queued]>
[2022-07-22 09:46:48,099] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 09:46:48,099] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-22 09:46:48,099] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 09:46:48,113] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): read_data> on 2022-07-22 06:46:44.015483+00:00
[2022-07-22 09:46:48,116] {standard_task_runner.py:52} INFO - Started process 24964 to run task
[2022-07-22 09:46:48,118] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'traffic_flow_dag', 'read_data', 'manual__2022-07-22T06:46:44.015483+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_data_loader.py', '--cfg-path', '/tmp/tmpsxk9x6jw', '--error-file', '/tmp/tmp58fwaevs']
[2022-07-22 09:46:48,119] {standard_task_runner.py:80} INFO - Job 10: Subtask read_data
[2022-07-22 09:46:48,132] {logging_mixin.py:115} WARNING - /home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/configuration.py:532 DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
[2022-07-22 09:46:48,149] {task_command.py:371} INFO - Running <TaskInstance: traffic_flow_dag.read_data manual__2022-07-22T06:46:44.015483+00:00 [running]> on host hp-HP-Pavilion-Laptop-15-eg0xxx
[2022-07-22 09:46:48,181] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tesfaye
AIRFLOW_CTX_DAG_ID=traffic_flow_dag
AIRFLOW_CTX_TASK_ID=read_data
AIRFLOW_CTX_EXECUTION_DATE=2022-07-22T06:46:44.015483+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-22T06:46:44.015483+00:00
[2022-07-22 09:46:48,181] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/hp/airflow/dags/create_dag_data_loader.py", line 39, in read_data
    df = pd.read_csv(
  File "/home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 665, in read_csv
    kwds_defaults = _refine_defaults_read(
  File "/home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1538, in _refine_defaults_read
    raise ValueError(
ValueError: Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator. Hence it is not allowed to use the line terminator as separator.
[2022-07-22 09:46:48,184] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=traffic_flow_dag, task_id=read_data, execution_date=20220722T064644, start_date=20220722T064648, end_date=20220722T064648
[2022-07-22 09:46:48,192] {standard_task_runner.py:92} ERROR - Failed to execute job 10 for task read_data (Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator. Hence it is not allowed to use the line terminator as separator.; 24964)
[2022-07-22 09:46:48,210] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-22 09:46:48,237] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
