[2022-07-22 09:41:18,820] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: traffic_flow_dag.read_data manual__2022-07-22T06:41:14.580349+00:00 [queued]>
[2022-07-22 09:41:18,824] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: traffic_flow_dag.read_data manual__2022-07-22T06:41:14.580349+00:00 [queued]>
[2022-07-22 09:41:18,824] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 09:41:18,824] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-22 09:41:18,824] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 09:41:18,832] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): read_data> on 2022-07-22 06:41:14.580349+00:00
[2022-07-22 09:41:18,834] {standard_task_runner.py:52} INFO - Started process 23066 to run task
[2022-07-22 09:41:18,835] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'traffic_flow_dag', 'read_data', 'manual__2022-07-22T06:41:14.580349+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_data_loader.py', '--cfg-path', '/tmp/tmpv1ab79cl', '--error-file', '/tmp/tmppqra86up']
[2022-07-22 09:41:18,836] {standard_task_runner.py:80} INFO - Job 9: Subtask read_data
[2022-07-22 09:41:18,845] {logging_mixin.py:115} WARNING - /home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/configuration.py:532 DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
[2022-07-22 09:41:18,859] {task_command.py:371} INFO - Running <TaskInstance: traffic_flow_dag.read_data manual__2022-07-22T06:41:14.580349+00:00 [running]> on host hp-HP-Pavilion-Laptop-15-eg0xxx
[2022-07-22 09:41:18,884] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tesfaye
AIRFLOW_CTX_DAG_ID=traffic_flow_dag
AIRFLOW_CTX_TASK_ID=read_data
AIRFLOW_CTX_EXECUTION_DATE=2022-07-22T06:41:14.580349+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-22T06:41:14.580349+00:00
[2022-07-22 09:41:18,884] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/hp/airflow/dags/create_dag_data_loader.py", line 39, in read_data
    df = pd.read_csv(
  File "/home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 665, in read_csv
    kwds_defaults = _refine_defaults_read(
  File "/home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1538, in _refine_defaults_read
    raise ValueError(
ValueError: Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator. Hence it is not allowed to use the line terminator as separator.
[2022-07-22 09:41:18,886] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=traffic_flow_dag, task_id=read_data, execution_date=20220722T064114, start_date=20220722T064118, end_date=20220722T064118
[2022-07-22 09:41:18,893] {standard_task_runner.py:92} ERROR - Failed to execute job 9 for task read_data (Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator. Hence it is not allowed to use the line terminator as separator.; 23066)
[2022-07-22 09:41:18,927] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-22 09:41:18,944] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
