[2022-07-22 14:06:04,026] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: load_data.load_dataset scheduled__2022-07-06T02:00:00+00:00 [queued]>
[2022-07-22 14:06:04,029] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: load_data.load_dataset scheduled__2022-07-06T02:00:00+00:00 [queued]>
[2022-07-22 14:06:04,029] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 14:06:04,029] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-07-22 14:06:04,029] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 14:06:04,039] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): load_dataset> on 2022-07-06 02:00:00+00:00
[2022-07-22 14:06:04,040] {standard_task_runner.py:52} INFO - Started process 15801 to run task
[2022-07-22 14:06:04,042] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'load_data', 'load_dataset', 'scheduled__2022-07-06T02:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_data_loader.py', '--cfg-path', '/tmp/tmp1ui3cjjw', '--error-file', '/tmp/tmp_htjhwwi']
[2022-07-22 14:06:04,043] {standard_task_runner.py:80} INFO - Job 14: Subtask load_dataset
[2022-07-22 14:06:04,054] {logging_mixin.py:115} WARNING - /home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/configuration.py:532 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-22 14:06:04,055] {logging_mixin.py:115} WARNING - /home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/configuration.py:532 DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
[2022-07-22 14:06:04,069] {task_command.py:371} INFO - Running <TaskInstance: load_data.load_dataset scheduled__2022-07-06T02:00:00+00:00 [running]> on host hp-HP-Pavilion-Laptop-15-eg0xxx
[2022-07-22 14:06:04,097] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tesfaye
AIRFLOW_CTX_DAG_ID=load_data
AIRFLOW_CTX_TASK_ID=load_dataset
AIRFLOW_CTX_EXECUTION_DATE=2022-07-06T02:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-06T02:00:00+00:00
[2022-07-22 14:06:04,116] {base.py:68} INFO - Using connection ID 'postgres_connection' for task execution.
[2022-07-22 14:06:04,127] {sql.py:255} INFO - Running statement: COPY raw_data FROM '/home/hp/Downloads/dataset.csv' WITH DELIMITER AS ';' NULL AS '\null' CSV HEADER;, parameters: None
[2022-07-22 14:06:04,129] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 234, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 260, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.BadCopyFileFormat: extra data after last expected column
CONTEXT:  COPY raw_data, line 2: "1; Motorcycle; 107.61; 17.608581; 37.977484; 23.737106; 13.4787; 0.0466; -0.0660; 38.400000; 37.9774..."

[2022-07-22 14:06:04,132] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=load_data, task_id=load_dataset, execution_date=20220706T020000, start_date=20220722T110604, end_date=20220722T110604
[2022-07-22 14:06:04,141] {standard_task_runner.py:92} ERROR - Failed to execute job 14 for task load_dataset (extra data after last expected column
CONTEXT:  COPY raw_data, line 2: "1; Motorcycle; 107.61; 17.608581; 37.977484; 23.737106; 13.4787; 0.0466; -0.0660; 38.400000; 37.9774..."
; 15801)
[2022-07-22 14:06:04,174] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-22 14:06:04,192] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
